version: '3.7'

services:
  logger:
    build: ./Logger
    networks:
      - DDS
  vectorpublisher:
    build: ./VectorPublisher
    networks:
      - DDS
  agent:
    build: ./Agent
    networks:
      - DDS
  clientone:
    build: ./ClientOne
    networks:
      - DDS
     
networks:
  DDS: