version: '3.7'

services:
  logger:
    build: ./Logger
    restart: always
    networks:
      DDS:
        ipv4_address: 172.16.238.44
  vectorpublisher:
    build: ./VectorPublisher
    restart: always
    networks:
      DDS:
        ipv4_address: 172.16.238.45
  agent:
    build: ./Agent
    networks:
      DDS:
        ipv4_address: 172.16.238.2
#  clientone:
#    build: ./ClientOne
#    networks:
#      DDS:
#        ipv4_address: 172.16.238.3
  clienttwo:
    build: ./ClientTwo
    restart: always
    networks:
      DDS:
        ipv4_address: 172.16.238.4
  clientthree:
    build: ./ClientThree
    restart: always
    networks:
      DDS:
        ipv4_address: 172.16.238.232
     
networks:
  DDS:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24